# Use official Python image from Docker Hub as base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt to the container
COPY backend/requirements.txt /app/

# Install Flask and other dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY backend /app/

# Expose port 5000 to be able to access the Flask app
EXPOSE 5000

# Set the environment variable for Flask app
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# Command to run the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
